- name: Tomcat provision
  hosts : node_1
  become: yes

  vars:
    tomcat_version: 8.5.46
    java_version: 1.8.0
    user_name: tomcat
    tomcat_archive_url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    tomcat_archive_dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz

  tasks:
    - name: Add EPEL repository
      yum:
        name: epel-release
        state: present

    - name: Install Java 8 CentOS
      yum:
        name: java-{{ java_version }}-openjdk
        state: present 

    - name: Add tomcat group
      group:
        name: '{{ user_name }}'

    - name: Add "tomcat" user
      user:
        name: '{{ user_name }}'
        group: '{{ user_name }}'
        createhome: no
        system: yes

    - name: Create CATALINA_HOME
      file:
        path: /opt/{{ user_name }}
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        state: directory

    - name: Download Tomcat
      get_url:
        url: "{{ tomcat_archive_url }}"
        dest: "{{ tomcat_archive_dest }}"

    - name: Extract tomcat archive
      unarchive:
        src: "{{ tomcat_archive_dest }}"
        dest: /opt/{{ user_name }}
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        remote_src: True

    - name: Deploy Systemd File
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service

    - name: Start and enable tomcat
      service:
        daemon_reload: yes
        name: '{{ user_name }}'
        state: started
        enabled: yes
   
    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open tomcat port on the firewall
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: yes
